# start from R&D image containing audio utilities and gpu support
FROM dev-registry.deez.re/research/dzr_audio_gpu:latest




# install jupyter
RUN conda install jupyter
RUN jupyter notebook --generate-config
RUN echo "c.NotebookApp.token = u''" >> ~/.jupyter/jupyter_notebook_config.py

# install git
RUN sudo apt-get update && \
    sudo  apt-get upgrade -y && \
    sudo apt-get install -y git

RUN sudo apt-get install nano

# clone inside image github repository
#RUN git clone https://github.com/KarimMibrahim/per_class_cnn_experiment.git /srv/workspace/research/per_class
#ENV PYTHONPATH=$PYTHONPATH:/srv/workspace/research/per_class

# install requirements
#COPY requirements.txt requirements.txt
#RUN pip install --upgrade pip
#RUN pip install -r requirements.txt
RUN pip install seaborn
#RUN rm requirements.txt
#RUN sudo pip install --upgrade keras

ENV CUDA_VISIBLE_DEVICES=3

#RUN apt-get install -y nano

#RUN mkdir /my_data
#RUN cp -R /src_code/repo/GroundTruth /my_data/GroundTruth
#RUN chmod -R a+w /my_data


#WORKDIR /src_code/repo

#USER deezer





